%%%
% TEST
% % DegreeSimilarity 
% Returns a matrix of similarities in degree
% @param: G - The matrix on which to calculacte centrality
% @param: types - vector of types
% @return: centralities - Returns a vector of centralities
%%%
classdef TestDegreeSimilarity < matlab.unittest.TestCase
    properties (ClassSetupParameter)
        identities = {[1,1,1,1]',[0,0,0,0]',[1,-1,1,-1]',[-1,1,-1,1]',[-1,-1,-1,-1]'};
    end
    properties (TestParameter)
    	matrices=struct('Empty', ...
    		[0,0,0,0; ...
    		 0,0,0,0; ...
    		 0,0,0,0; ...
    		 0,0,0,0], ...
    		'SymPairs', ... 
    		[0,1,0,0; ...
    		 1,0,0,0; ...
    		 0,0,0,1; ...
    		 0,0,1,0], ...
    		'SymCentral', ... 
    		[0,1,1,1; ...
    		 1,0,0,0; ...
    		 1,0,0,0; ...
    		 1,0,0,0], ...
    		'SymFollower', ... 
    		[0,1,0,0; ...
    		 1,0,1,1; ...
    		 0,1,0,0; ...
    		 0,1,0,0], ...
    		'Central', ... 
    		[0,0,0,0; ...
    		 1,0,0,0; ...
    		 1,0,0,0; ...
    		 1,0,0,0], ...
    		'Follower', ... 
    		[0,1,0,0; ...
    		 0,0,0,0; ...
    		 0,1,0,0; ...
    		 0,1,0,0])
        	typecents=struct('Empty', [0,0] , ...
    		'SymPairs', [0,0] , ... 
    		'SymCentral', [2,2], ... 
    		'SymFollower', [-2,-2],... 
    		'Central', [-1,3],... 
    		'Follower', [1,-3])
    end
     methods (Test)
        function testSignage(testCase, identities, matrices)
            centralities=TypeCentralities(matrices, identities);
            if identities(1)>=0
                testCase.verifyGreaterThanOrEqual(testCase,centralities.outcentrality(1),0);
                testCase.verifyGreaterThanOrEqual(testCase,centralities.incentrality(1),0);
                testCase.verifyGreaterThanOrEqual(testCase,centralities.influencecentrality(1),0);
            else
                testCase.verifyLessThanOrEqual(testCase,centralities.outcentrality(1),0);
                testCase.verifyLessThanOrEqual(testCase,centralities.incentrality(1),0);
                testCase.verifyLessThanOrEqual(testCase,centralities.influencecentrality(1),0);                
            end
        end
     end    
end
