%% Work in Progress
classdef TestDegreeSimilarity < matlab.unittest.TestCase

    properties (TestParameter)
    	matrices=struct('Empty', ...
    		[0,0,0,0; ...
    		 0,0,0,0; ...
    		 0,0,0,0; ...
    		 0,0,0,0], ...
    		'SymPairs', ... 
    		[0,1,0,0; ...
    		 1,0,0,0; ...
    		 0,0,0,1; ...
    		 0,0,1,0], ...
    		'SymCentral', ... 
    		[0,1,1,1; ...
    		 1,0,0,0; ...
    		 1,0,0,0; ...
    		 1,0,0,0], ...
    		'SymFollower', ... 
    		[0,1,0,0; ...
    		 1,0,1,1; ...
    		 0,1,0,0; ...
    		 0,1,0,0], ...
    		'Central', ... 
    		[0,0,0,0; ...
    		 1,0,0,0; ...
    		 1,0,0,0; ...
    		 1,0,0,0], ...
    		'Follower', ... 
    		[0,1,0,0; ...
    		 0,0,0,0; ...
    		 0,1,0,0; ...
    		 0,1,0,0])
        	degreediffs=struct('Empty', [0,0] , ...
    		'SymPairs', [0,0] , ... 
    		'SymCentral', [2,2], ... 
    		'SymFollower', [-2,-2],... 
    		'Central', [-1,3],... 
    		'Follower', [1,-3])
    end
     methods (Test, ParameterCombination='sequential')
        function testInOutDifferences(testCase, matrices, degreediffs)
            [outdegreesim,indegreesim]=DegreeSimilarity(matrices);
            testvec=[outdegreesim(1,2),indegreesim(1,2)];
            testCase.verifyEqual(testvec,...
                degreediffs)
        end
     end
    
end
